// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ6GXBwiFPTvov7HksBaca7xr5ZlET46w',
    appId: '1:1079712193430:web:ea86e039f98f31a2ce9bb7',
    messagingSenderId: '1079712193430',
    projectId: 'chat-app-32834',
    authDomain: 'chat-app-32834.firebaseapp.com',
    storageBucket: 'chat-app-32834.firebasestorage.app',
    measurementId: 'G-FE708244GM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGUyZRW_boz_oombjJbNvEN1tE7iu7oRI',
    appId: '1:1079712193430:android:df284e711a9f36d2ce9bb7',
    messagingSenderId: '1079712193430',
    projectId: 'chat-app-32834',
    storageBucket: 'chat-app-32834.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpCoRd-2o_4useNfBDdXyphqb0YrUpgLw',
    appId: '1:1079712193430:ios:cbcfe193ba120e84ce9bb7',
    messagingSenderId: '1079712193430',
    projectId: 'chat-app-32834',
    storageBucket: 'chat-app-32834.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpCoRd-2o_4useNfBDdXyphqb0YrUpgLw',
    appId: '1:1079712193430:ios:cbcfe193ba120e84ce9bb7',
    messagingSenderId: '1079712193430',
    projectId: 'chat-app-32834',
    storageBucket: 'chat-app-32834.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ6GXBwiFPTvov7HksBaca7xr5ZlET46w',
    appId: '1:1079712193430:web:f348d04175f53d3ece9bb7',
    messagingSenderId: '1079712193430',
    projectId: 'chat-app-32834',
    authDomain: 'chat-app-32834.firebaseapp.com',
    storageBucket: 'chat-app-32834.firebasestorage.app',
    measurementId: 'G-2DM660RE7X',
  );
}
